### ISSUE TITLE
Question: orignalFilename(s) from request-collection?

### ISSUE THREAD

**Issue by Kapaski** [mulesoft/mule-module-requester#15]
Hello,

I am using the mulerequester's 'request-collection' option to an FTP endpoint, where 2 files were hosted. I found the payload out of mulerequester becomes collection, and not like the 'request' mode, there is no longer a header property 'originalFilename' in each of the element of that collection (I was using for-each scope to that collection)

is that by design or I did something wrong to get the filenames? your help will be appreciated, thanks very much.

James

**Comment by sbeltramini** [comment]
James,

The request-collection operation retrieves a collection of MuleMessage so you'll have all the properties available in that MuleMessage as if you requested that resource alone.

However, the scope and properties available depend on the version of Mule (originalFilename was moved from Outbound to Inbound in between versions).

Do you get different properties in the same Mule version if you use request and request-collection?

**Comment by Kapaski** [comment]
Thanks for reply @sbeltramini 

I found the issue is from my side - not familiar with the connector... so when I posted this issue, I didn't know if you get payload out of 'request-collection', it will be a collection of payloads from each message, and when I used #[message.getMessageAsArray()] with something like a 'for-each' scope, I can see each message with their original headers. So I am happy to close this issue off.
