### ISSUE TITLE
ftp endpoint

### ISSUE THREAD

**Issue by akm12** [mulesoft/mule-module-requester#16]
hi,

when trying to use your requester with a FTP connector, settings FTP-Endpoint as resource gives a FTP Endpoint" is malformed and cannot be parsed

I am probably missing something really simple but sadly the example are all with an HTTP connector 

thanks for any info or help

**Comment by sbeltramini** [comment]
Can you show the configuration you have?

**Comment by akm12** [comment]
I went with this http://ricston.com/blog/catching-sftps-connection-failure-exceptions/comment-page-1/#comment-185225

(I am new to mule and been looking for a way to intercept connection errors on FTP and this seems to be the way to do it)

so I tried that example, changed it to FTP and added an FTP connector to it, which if I get the idea right should be triggers bij the requester.

   <mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>
    <flow name="FTP" doc:name="FTP">
        <ftp:inbound-endpoint host="localhost" port="21" path="/out" user="test" password="test" binary="false" responseTimeout="10000" doc:name="FTP"/>
    </flow>
<flow name="ftp-mainflow" doc:name="ftp-mainflow">
	<poll frequency="5000" doc:name="Poll">
		<mulerequester:request config-ref="Mule_Requester"
			resource="FTP-Endpoint" doc:name="Mule Requester" />
	</poll>
	
	<logger level="INFO"
		message="Received File #[message.inboundProperties.originalFileName]"
		doc:name="Logger" />
	<choice-exception-strategy doc:name="Choice Exception Strategy">
		<catch-exception-strategy
			when="#[exception.causedBy(java.net.ConnectException)]" doc:name="Connect Exception Strategy">
			<logger level="ERROR" message="Connect Exception: #[exception.message]."
				doc:name="Logger" />
		</catch-exception-strategy>
		<catch-exception-strategy
			when="#[exception.causedBy(java.io.IOException)]" doc:name="IO Exception Strategy">
			<logger level="ERROR" message="IO Exception: #[exception.message]."
				doc:name="Logger" />
		</catch-exception-strategy>
	</choice-exception-strategy>
</flow>

**Comment by akm12** [comment]
<mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>
    <flow name="FTP" doc:name="FTP">
        <ftp:inbound-endpoint host="localhost" port="21" path="/out" user="test" password="test" binary="false" responseTimeout="10000" doc:name="FTP"/>
    </flow>
<flow name="ftp-mainflow" doc:name="ftp-mainflow">
	<poll frequency="5000" doc:name="Poll">
		<mulerequester:request config-ref="Mule_Requester"
			resource="FTP-Endpoint" doc:name="Mule Requester" />
	</poll>
	
	<logger level="INFO"
		message="Received File #[message.inboundProperties.originalFileName]"
		doc:name="Logger" />
	<choice-exception-strategy doc:name="Choice Exception Strategy">
		<catch-exception-strategy
			when="#[exception.causedBy(java.net.ConnectException)]" doc:name="Connect Exception Strategy">
			<logger level="ERROR" message="Connect Exception: #[exception.message]."
				doc:name="Logger" />
		</catch-exception-strategy>
		<catch-exception-strategy
			when="#[exception.causedBy(java.io.IOException)]" doc:name="IO Exception Strategy">
			<logger level="ERROR" message="IO Exception: #[exception.message]."
				doc:name="Logger" />
		</catch-exception-strategy>
	</choice-exception-strategy>
</flow>

**Comment by sbeltramini** [comment]
Could you make sure you format comment properly? I cannot see the full configuration, it's showing broken.

**Comment by akm12** [comment]
should be better now

**Comment by sbeltramini** [comment]
There are a few errors in that configuration:
1. Flows cannot have only a message source without message processors. In your case you have a flow with just an inbound endpoint. 
2. The endpoint you want to reference must be a global one.

This is the working configuration:
```xml
    <mulerequester:config name="Mule_Requester" doc:name="Mule Requester" />
    
   <ftp:endpoint name="FTP-Endpoint" host="localhost" port="21" path="/out" user="test" password="test" binary="false" responseTimeout="10000" doc:name="FTP" />
    
    <flow name="ftp-mainflow" doc:name="ftp-mainflow">
        <poll frequency="5000" doc:name="Poll">
            <mulerequester:request config-ref="Mule_Requester" resource="FTP-Endpoint" doc:name="Mule Requester" />
        </poll>

        <logger level="INFO" message="Received File #[message.inboundProperties.originalFileName]" doc:name="Logger" />
        <choice-exception-strategy doc:name="Choice Exception Strategy">
            <catch-exception-strategy when="#[exception.causedBy(java.net.ConnectException)]" doc:name="Connect Exception Strategy">
                <logger level="ERROR" message="Connect Exception: #[exception.message]." doc:name="Logger" />
            </catch-exception-strategy>
            <catch-exception-strategy when="#[exception.causedBy(java.io.IOException)]" doc:name="IO Exception Strategy">
                <logger level="ERROR" message="IO Exception: #[exception.message]." doc:name="Logger" />
            </catch-exception-strategy>
        </choice-exception-strategy>
    </flow>
```

**Comment by akm12** [comment]
thank you, I forgot to put the File as endpoint in the flow I posted before.
In your working example its find the file but I got nowhere to put the File endpoint connector.

I got lots to learn still ;)   
thank you though.

**Comment by akm12** [comment]
Got it working, thanks for the help !!

**Comment by sbeltramini** [comment]
You're welcome. Glad to see it worked for you.
