### ISSUE TITLE
@Inject causing failure during Spring Auto Scan

### ISSUE THREAD

**Issue by k2merlinsix** [mulesoft/mule-module-requester#17]
@Processor
    @Inject
    public void requestCollection(MuleEvent muleEvent, String resource, @Optional @Default("1000") long timeout, @Optional String returnClass,
    		@Optional Boolean throwExceptionOnTimeout, @Optional @Default("-1") int count) throws MuleException 
    {

The @Inject annotation needs to be removed and follow the same annotation pattern of the request I believe (unless there is a reason the @Inject is needed here) We enable the spring autoscan in some of our spring components, this causes the spring runtime try to find any spring beans that match this method signature so this causes the application to fail with an unable to find MuleEvent Spring Bean.

**Comment by sbeltramini** [comment]
This was fixed in the latest release.
Thanks.
