### ISSUE TITLE
Studio plugin generation fails on case-sensitive file systems

### ISSUE THREAD

**Issue by dfeist** [mulesoft/mule-module-requester#2]
This is caused by filenames of having different cases in annotated connector and on the in the icons directory.

[ERROR] Failed to execute goal org.mule.tools.devkit:mule-devkit-maven-plugin:3.4.1:generate-sources (default-generate-sources) on project mule-requester: An error ocurred while the DevKit was generating Java code. Check the logs for further details. -> [Help 1]

**Comment by sbeltramini** [comment]
I am not able to reproduce this with the latest version.
