### ISSUE TITLE
Connector not being disposed after use

### ISSUE THREAD

**Issue by dietervanhoof** [mulesoft/mule-module-requester#22]
I've been using mule-module-requester for reading files from an FTP location on demand.
The connector gets initialized and works as expected but never closes or disposes itself until the whole application is undeployed.

This makes the shutdown process long and full of these, this is only after about 12 hours of running:

```15:32:06,198 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.dispatcher.1659419797 Object is: FtpMessageDispatcher```
```15:32:06,234 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.dispatcher.1659419797 Object is: FtpMessageDispatcher```
```15:32:06,236 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.472403534 Object is: EEFtpMessageRequester```
```15:32:06,368 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.472403534 Object is: EEFtpMessageRequester```
```15:32:06,369 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1900885313 Object is: EEFtpMessageRequester```
```15:32:06,443 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1900885313 Object is: EEFtpMessageRequester```
```15:32:06,444 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1211725335 Object is: EEFtpMessageRequester```
```15:32:06,540 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1211725335 Object is: EEFtpMessageRequester```
```15:32:06,540 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.668789081 Object is: EEFtpMessageRequester```
```15:32:06,636 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.668789081 Object is: EEFtpMessageRequester```
```15:32:06,637 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.239011724 Object is: EEFtpMessageRequester```
```15:32:06,724 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.239011724 Object is: EEFtpMessageRequester```
```15:32:06,725 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1048649645 Object is: EEFtpMessageRequester```
```15:32:06,831 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1048649645 Object is: EEFtpMessageRequester```
```15:32:06,832 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.35921935 Object is: EEFtpMessageRequester```
```15:32:06,920 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.35921935 Object is: EEFtpMessageRequester```
```15:32:06,920 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.468760657 Object is: EEFtpMessageRequester```
```15:32:07,028 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.468760657 Object is: EEFtpMessageRequester```
```15:32:07,028 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.900300045 Object is: EEFtpMessageRequester```
```15:32:07,160 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.900300045 Object is: EEFtpMessageRequester```
```15:32:07,160 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1511822274 Object is: EEFtpMessageRequester```
```15:32:07,277 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1511822274 Object is: EEFtpMessageRequester```
```15:32:07,278 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.36450273 Object is: EEFtpMessageRequester```
```15:32:07,367 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.36450273 Object is: EEFtpMessageRequester```
```15:32:07,368 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.395909404 Object is: EEFtpMessageRequester```
```15:32:07,468 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.395909404 Object is: EEFtpMessageRequester```
```15:32:07,468 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1772717602 Object is: EEFtpMessageRequester```
```15:32:07,567 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1772717602 Object is: EEFtpMessageRequester```
```15:32:07,567 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.99629601 Object is: EEFtpMessageRequester```
```15:32:07,652 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.99629601 Object is: EEFtpMessageRequester```
```15:32:07,653 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1172716288 Object is: EEFtpMessageRequester```
```15:32:07,732 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1172716288 Object is: EEFtpMessageRequester```
```15:32:07,732 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1643954034 Object is: EEFtpMessageRequester```
```15:32:07,823 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1643954034 Object is: EEFtpMessageRequester```
```15:32:07,824 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1365495425 Object is: EEFtpMessageRequester```
```15:32:07,924 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1365495425 Object is: EEFtpMessageRequester```
```15:32:07,925 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.116733657 Object is: EEFtpMessageRequester```
```15:32:08,018 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.116733657 Object is: EEFtpMessageRequester```
```15:32:08,019 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.2075960351 Object is: EEFtpMessageRequester```
```15:32:08,116 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.2075960351 Object is: EEFtpMessageRequester```
```15:32:08,116 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1760760575 Object is: EEFtpMessageRequester```
```15:32:08,205 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1760760575 Object is: EEFtpMessageRequester```
```15:32:08,206 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1392921048 Object is: EEFtpMessageRequester```
```15:32:08,320 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1392921048 Object is: EEFtpMessageRequester```
```15:32:08,321 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.445730445 Object is: EEFtpMessageRequester```
```15:32:08,400 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.445730445 Object is: EEFtpMessageRequester```
```15:32:08,401 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1225465576 Object is: EEFtpMessageRequester```
```15:32:08,503 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1225465576 Object is: EEFtpMessageRequester```
```15:32:08,504 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.606709833 Object is: EEFtpMessageRequester```
```15:32:08,592 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.606709833 Object is: EEFtpMessageRequester```
```15:32:08,592 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1895777993 Object is: EEFtpMessageRequester```
```15:32:08,687 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1895777993 Object is: EEFtpMessageRequester```
```15:32:08,688 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.107521414 Object is: EEFtpMessageRequester```
```15:32:08,783 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.107521414 Object is: EEFtpMessageRequester```
```15:32:08,784 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.109797200 Object is: EEFtpMessageRequester```
```15:32:08,879 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.109797200 Object is: EEFtpMessageRequester```
```15:32:08,880 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.925905468 Object is: EEFtpMessageRequester```
```15:32:08,996 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.925905468 Object is: EEFtpMessageRequester```
```15:32:08,996 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1954601928 Object is: EEFtpMessageRequester```
```15:32:09,092 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1954601928 Object is: EEFtpMessageRequester```
```15:32:09,093 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.952178145 Object is: EEFtpMessageRequester```
```15:32:09,184 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.952178145 Object is: EEFtpMessageRequester```
```15:32:09,184 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1017665521 Object is: EEFtpMessageRequester```
```15:32:09,284 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1017665521 Object is: EEFtpMessageRequester```
```15:32:09,284 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.63495731 Object is: EEFtpMessageRequester```
```15:32:09,388 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.63495731 Object is: EEFtpMessageRequester```
```15:32:09,389 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1067446123 Object is: EEFtpMessageRequester```
```15:32:09,491 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1067446123 Object is: EEFtpMessageRequester```
```15:32:09,492 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1240846550 Object is: EEFtpMessageRequester```
```15:32:09,584 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1240846550 Object is: EEFtpMessageRequester```
```15:32:09,584 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.478966365 Object is: EEFtpMessageRequester```
```15:32:09,668 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.478966365 Object is: EEFtpMessageRequester```
```15:32:09,668 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1980576145 Object is: EEFtpMessageRequester```
```15:32:09,756 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1980576145 Object is: EEFtpMessageRequester```
```15:32:09,757 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1578352571 Object is: EEFtpMessageRequester```
```15:32:09,843 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1578352571 Object is: EEFtpMessageRequester```
```15:32:09,844 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.208369982 Object is: EEFtpMessageRequester```
```15:32:09,936 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.208369982 Object is: EEFtpMessageRequester```
```15:32:09,936 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.862923391 Object is: EEFtpMessageRequester```
```15:32:10,024 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.862923391 Object is: EEFtpMessageRequester```
```15:32:10,025 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.609672063 Object is: EEFtpMessageRequester```
```15:32:10,119 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.609672063 Object is: EEFtpMessageRequester```
```15:32:10,120 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.428682391 Object is: EEFtpMessageRequester```
```15:32:10,212 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.428682391 Object is: EEFtpMessageRequester```
```15:32:10,212 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.795819463 Object is: EEFtpMessageRequester```
```15:32:10,312 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.795819463 Object is: EEFtpMessageRequester```
```15:32:10,312 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.149113571 Object is: EEFtpMessageRequester```
```15:32:10,403 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.149113571 Object is: EEFtpMessageRequester```
```15:32:10,404 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1307054116 Object is: EEFtpMessageRequester```
```15:32:10,500 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1307054116 Object is: EEFtpMessageRequester```
```15:32:10,501 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.534485381 Object is: EEFtpMessageRequester```
```15:32:10,599 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.534485381 Object is: EEFtpMessageRequester```
```15:32:10,600 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1069331868 Object is: EEFtpMessageRequester```
```15:32:10,700 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1069331868 Object is: EEFtpMessageRequester```
```15:32:10,701 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.731650207 Object is: EEFtpMessageRequester```
```15:32:10,796 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.731650207 Object is: EEFtpMessageRequester```
```15:32:10,797 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1988600948 Object is: EEFtpMessageRequester```
```15:32:10,900 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1988600948 Object is: EEFtpMessageRequester```
```15:32:10,901 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.849545866 Object is: EEFtpMessageRequester```
```15:32:11,028 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.849545866 Object is: EEFtpMessageRequester```
```15:32:11,029 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.377990309 Object is: EEFtpMessageRequester```
```15:32:11,164 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.377990309 Object is: EEFtpMessageRequester```
```15:32:11,165 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1519639362 Object is: EEFtpMessageRequester```
```15:32:11,251 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1519639362 Object is: EEFtpMessageRequester```
```15:32:11,252 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.636744704 Object is: EEFtpMessageRequester```
```15:32:11,375 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.636744704 Object is: EEFtpMessageRequester```
```15:32:11,376 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.935567373 Object is: EEFtpMessageRequester```
```15:32:11,503 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.935567373 Object is: EEFtpMessageRequester```
```15:32:11,504 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.205986841 Object is: EEFtpMessageRequester```
```15:32:11,599 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.205986841 Object is: EEFtpMessageRequester```
```15:32:11,600 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.155618161 Object is: EEFtpMessageRequester```
```15:32:11,716 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.155618161 Object is: EEFtpMessageRequester```
```15:32:11,717 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1597055087 Object is: EEFtpMessageRequester```
```15:32:11,803 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1597055087 Object is: EEFtpMessageRequester```
```15:32:11,804 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1503637052 Object is: EEFtpMessageRequester```
```15:32:11,891 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1503637052 Object is: EEFtpMessageRequester```
```15:32:11,892 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1946580968 Object is: EEFtpMessageRequester```
```15:32:11,977 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1946580968 Object is: EEFtpMessageRequester```
```15:32:11,977 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1465593476 Object is: EEFtpMessageRequester```
```15:32:12,086 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1465593476 Object is: EEFtpMessageRequester```
```15:32:12,087 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.674087907 Object is: EEFtpMessageRequester```
```15:32:12,177 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.674087907 Object is: EEFtpMessageRequester```
```15:32:12,177 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1387499324 Object is: EEFtpMessageRequester```
```15:32:12,321 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1387499324 Object is: EEFtpMessageRequester```
```15:32:12,321 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.583394030 Object is: EEFtpMessageRequester```
```15:32:12,440 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.583394030 Object is: EEFtpMessageRequester```
```15:32:12,440 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.588182138 Object is: EEFtpMessageRequester```
```15:32:12,543 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.588182138 Object is: EEFtpMessageRequester```
```15:32:12,544 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1636135585 Object is: EEFtpMessageRequester```
```15:32:12,621 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1636135585 Object is: EEFtpMessageRequester```
```15:32:12,621 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.142644735 Object is: EEFtpMessageRequester```
```15:32:12,744 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.142644735 Object is: EEFtpMessageRequester```
```15:32:12,744 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.359153195 Object is: EEFtpMessageRequester```
```15:32:12,841 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.359153195 Object is: EEFtpMessageRequester```
```15:32:12,842 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1006675186 Object is: EEFtpMessageRequester```
```15:32:12,943 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1006675186 Object is: EEFtpMessageRequester```
```15:32:12,944 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.184504100 Object is: EEFtpMessageRequester```
```15:32:13,048 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.184504100 Object is: EEFtpMessageRequester```
```15:32:13,049 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.653148071 Object is: EEFtpMessageRequester```
```15:32:13,156 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.653148071 Object is: EEFtpMessageRequester```
```15:32:13,156 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.997645383 Object is: EEFtpMessageRequester```
```15:32:13,265 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.997645383 Object is: EEFtpMessageRequester```
```15:32:13,266 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.210260835 Object is: EEFtpMessageRequester```
```15:32:13,380 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.210260835 Object is: EEFtpMessageRequester```
```15:32:13,380 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.442737710 Object is: EEFtpMessageRequester```
```15:32:13,488 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.442737710 Object is: EEFtpMessageRequester```
```15:32:13,489 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1951836482 Object is: EEFtpMessageRequester```
```15:32:13,588 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1951836482 Object is: EEFtpMessageRequester```
```15:32:13,588 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1929194711 Object is: EEFtpMessageRequester```
```15:32:13,679 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1929194711 Object is: EEFtpMessageRequester```
```15:32:13,680 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.307856769 Object is: EEFtpMessageRequester```
```15:32:13,795 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.307856769 Object is: EEFtpMessageRequester```
```15:32:13,796 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.2029761158 Object is: EEFtpMessageRequester```
```15:32:13,892 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.2029761158 Object is: EEFtpMessageRequester```
```15:32:13,893 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1475868645 Object is: EEFtpMessageRequester```
```15:32:13,976 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1475868645 Object is: EEFtpMessageRequester```
```15:32:13,976 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1902792655 Object is: EEFtpMessageRequester```
```15:32:14,084 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1902792655 Object is: EEFtpMessageRequester```
```15:32:14,084 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.676898595 Object is: EEFtpMessageRequester```
```15:32:14,211 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.676898595 Object is: EEFtpMessageRequester```
```15:32:14,212 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.148242359 Object is: EEFtpMessageRequester```
```15:32:14,311 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.148242359 Object is: EEFtpMessageRequester```
```15:32:14,312 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.755148348 Object is: EEFtpMessageRequester```
```15:32:14,400 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.755148348 Object is: EEFtpMessageRequester```
```15:32:14,400 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.125224614 Object is: EEFtpMessageRequester```
```15:32:14,501 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.125224614 Object is: EEFtpMessageRequester```
```15:32:14,501 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.571760043 Object is: EEFtpMessageRequester```
```15:32:14,597 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.571760043 Object is: EEFtpMessageRequester```
```15:32:14,598 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.2057655370 Object is: EEFtpMessageRequester```
```15:32:14,719 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.2057655370 Object is: EEFtpMessageRequester```
```15:32:14,720 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.266528365 Object is: EEFtpMessageRequester```
```15:32:14,804 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.266528365 Object is: EEFtpMessageRequester```
```15:32:14,804 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.883312578 Object is: EEFtpMessageRequester```
```15:32:14,903 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.883312578 Object is: EEFtpMessageRequester```
```15:32:14,904 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1151083638 Object is: EEFtpMessageRequester```
```15:32:15,000 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1151083638 Object is: EEFtpMessageRequester```
```15:32:15,000 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.143615541 Object is: EEFtpMessageRequester```
```15:32:15,103 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.143615541 Object is: EEFtpMessageRequester```
```15:32:15,104 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.939796158 Object is: EEFtpMessageRequester```
```15:32:15,198 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.939796158 Object is: EEFtpMessageRequester```
```15:32:15,198 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.184846151 Object is: EEFtpMessageRequester```
```15:32:15,288 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.184846151 Object is: EEFtpMessageRequester```
```15:32:15,288 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.1348338064 Object is: EEFtpMessageRequester```
```15:32:15,376 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.1348338064 Object is: EEFtpMessageRequester```
```15:32:15,376 org.mule.lifecycle.AbstractLifecycleManager: Stopping: FTP.requester.651987155 Object is: EEFtpMessageRequester```
```15:32:15,483 org.mule.lifecycle.AbstractLifecycleManager: Disposing: FTP.requester.651987155 Object is: EEFtpMessageRequester```

I also believe the connector does not close the connection after using it and I don't see how I would close it manually. This makes the FTP server timeout (5 minutes without activity) and also spam its logs full of messages.

**Comment by sbeltramini** [comment]
Thanks for reporting this.

However, it's not an issue in the Mule Requester Module but rather the way that Mule works when using requesters in general. The Mule Requester Module is an abstraction layer on top of Mule components and it delegates the request of the resources to each transport (FTP, File, etc.).

To show this, simply use this configuration:
```
    <ftp:endpoint name="ftpEndpoint" host="localhost" port="21" user="" password="" path="/s/tmp/testbla" />

    <flow name="main">
        <quartz:inbound-endpoint jobName="myServiceJob" repeatInterval="5000">
            <quartz:endpoint-polling-job>
                <quartz:job-endpoint ref="ftpEndpoint"/>
            </quartz:endpoint-polling-job>
        </quartz:inbound-endpoint> 
        <logger level="WARN"  />  
    </flow>
```

You will see the same behaviour as if using the Requester module but here it's not used at all, but it's Quartz calling the requester of the transport (EEFtpMessageRequester class in this example):
```
INFO  2016-03-22 17:54:32,282 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'connector.ftp.mule.default.requester.1515823555'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,414 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Disposing: 'connector.ftp.mule.default.requester.1515823555'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,414 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'connector.ftp.mule.default.requester.2046855961'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,537 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Disposing: 'connector.ftp.mule.default.requester.2046855961'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,537 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'connector.ftp.mule.default.requester.1791958689'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,662 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Disposing: 'connector.ftp.mule.default.requester.1791958689'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,663 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Stopping: 'connector.ftp.mule.default.requester.673424052'. Object is: EEFtpMessageRequester
INFO  2016-03-22 17:54:32,791 [WrapperListener_stop_runner] org.mule.lifecycle.AbstractLifecycleManager: Disposing: 'connector.ftp.mule.default.requester.673424052'. Object is: EEFtpMessageRequester
```
As for the second issue, again it's the same case: the Requester module just makes use of the underlying transport. In the case of FTP, the resource is being disposed as shown in org.mule.transport.ftp.FtpMessageRequester.doRequest(long):

```
        finally
        {
            connector.releaseFtp(endpoint.getEndpointURI(), client);
        }
```

If you believe that the first issue is valid, you would need to either report it with MuleSoft Support (if you are a customer) or as a JIRA (if you aren't a customer).
