### ISSUE TITLE
How to request JMS topic with "durable" attribute.

### ISSUE THREAD

**Issue by abhusari** [mulesoft/mule-module-requester#24]
I want to call  JMS topic with "durable" attribute of the jms:inbound. Is there any way to accomplish this with mule requestor.

**Comment by sbeltramini** [comment]
You can define the JMS endpoint as global and refer to it using the the endpoint's name.

**Comment by abhusari** [comment]
Thanks for the reply.

I have tried that, "durableName" attribute not allows in JMS global endpoint. It only allowed under jms:inbound-endpoint.

Is there workaround for it in Mule requester?
