### ISSUE TITLE
Can this handle large sized files?

### ISSUE THREAD

**Issue by vijayanganapathy** [mulesoft/mule-module-requester#26]
Is there any limitation on the size of files Mule Requester can pull from File/FTP/SFTP locations? We are looking to understand if this can be used to handle file sizes of 1GB to 20GB.

**Comment by sbeltramini** [comment]
Hello,
There are no limitations on this module itself, but there could be in the underlying transport. For more detail, please refer to the "Limitations" section.
Sebastian
