### ISSUE TITLE
How to retrieve FileName and FileSize ? 

### ISSUE THREAD

**Issue by devanad** [mulesoft/mule-module-requester#29]
Hi,

We are using following code to retrieve the file from SFTP location. 

		<mulerequester:request config-ref="FTP_Requester" resource="ftp://${ftp.inbound.root.user}:${ftp.inbound.root.password}@${ftp.inbound.root.host}:${ftp.inbound.root.port}${ftp.inbound.root.path}#[payload]" timeout="${ftp.edi.inbound.root.responseTimeout}" throwExceptionOnTimeout="false" doc:name="Mule Requester" />

Requester is not allowing to Retrieve the FileName in any of the properties, How do i retrieve the FileName and FileSize information of that object using MuleRequester ?

Thanks.

**Comment by PabloCamino** [comment]
Hello @devanad , the requester is supposed to be used to consume files from a given directory, when using FTP as the protocol, but not to specify a single file to download. You should use filters or application logic to decide how to process each file. Remember that the requester is just a convenience to call an endpoint, FTP in this case, which works by polling files from a directory, not by retrieving a specific file.
Regards.
