### ISSUE TITLE
this refers to requester-module v 1.3

### ISSUE THREAD

**Issue by PaulAndersonMule** [mulesoft/mule-module-requester#31]
the URL in here:

https://github.com/mulesoft/mule-module-requester#for-mulestudio

Download the update site zip file from the following location: https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/mule-module-requester/1.3/mule-module-requester-1.3-studio-plugin.zip

should refer to v1.5 instead of 1.3

**Comment by sbeltramini** [comment]
Thanks for reporting this, fixed now.
