### ISSUE TITLE
using one endpoint in two Mule Requester

### ISSUE THREAD

**Issue by msyaeful** [mulesoft/mule-module-requester#35]
Hi Team,

I have an issue:
There is two Mule Requester Module that use one Endpoint (SFTP Connector).
I use different annotation filename-regex-filter for both.
The problem is when the Mule Requester A executed the file that polled is that should be polled by Mule Requester B and vice versa.

Thanks and regards,
Syaeful

**Comment by PabloCamino** [comment]
It would seem that the name references are wrong. Share a snippet of code if you are still facing this issue. Best!
