### ISSUE TITLE
config-ref' is not allowed to appear in element 'mulerequester:request-collection'.

### ISSUE THREAD

**Issue by chiranjeevinalluri** [mulesoft/mule-module-requester#36]
When using requester of version 1.5
 <mulerequester:config name="Mule_Requester" doc:name="Mule Requester"/>
<mulerequester:request-collection resource="vm://payloadbatch" config-ref="Mule_Requester" doc:name="Mule Requester to read from VM" />

giving error as 
org.xml.sax.SAXParseException: cvc-complex-type.3.2.2: Attribute 'config-ref' is not allowed to appear in element 'mulerequester:request-collection'.

**Comment by sbeltramini** [comment]
Remove "mulerequester:config" completely and   config-ref="Mule_Requester"  from mulerequester:request-collection.
Configs are not required (nor supported) in the last version.
