### ISSUE TITLE
Request Collection

### ISSUE THREAD

**Issue by vsundar1** [mulesoft/mule-module-requester#40]
After the Request collection operation i am not able to read each files,
Can you let me know the usage of the request collection operations?

**Comment by PabloCamino** [comment]
A ForEach component should let you iterate through every item.
If you keep struggling with it, my suggestion would be to try with Mule 4.

**Comment by vsundar1** [comment]
Hi Pablo
Thanks , I can use for each, However my challenge is i want to get only *.xml files from that collection?
any suggestions for this.
Thanks

**Comment by PabloCamino** [comment]
The file transport allows you to use a filter and only get *.xml
